// import { Provider } from 'react-redux';
// import { wrapper } from '../store/store';

import './globals.css'
import Header from "@/app/components/Header";
import { Mulish } from 'next/font/google';
import Footer from "@/app/components/Footer";

const mulish = Mulish({
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  // const { store, props } = wrapper.useWrappedStore(rest);
  // const { pageProps } = props;

  return (
    <html lang="en" className={mulish.className}>
      <body>
        {/* <Provider store={store}> */}
          <Header />
            {children}
          <Footer />
        {/* </Provider> */}
      </body>
    </html>
  )
}
